### ISSUE TITLE
Problemi di visualizzazione - CSS Mancante

### ISSUE THREAD

**Issue by ricceri** [AAROC/addis-hackfest#1]
Console error: 
- Failed to load resourses (main.css .... image.png ) 
- Cannot find module "axios"

**Comment by brucellino** [comment]
Thanks @ricceri I am able to reproduce the error. Working on it.

**Comment by brucellino** [comment]
@ricceri Penso che ho risolto il problema. Potresti confermare per favore ? 
Fixed in 6f243c42b6
